# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: lelinhtinh
open_collective: de4js
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: lelinhtinh
otechie: # Replace with a single Otechie username
custom: ['https://flattr.com/@lelinhtinh', 'https://nhantien.momo.vn/VF3uGGDacJx']
